# required input from environment:
# $(BIOINFOCONFDIR) $(BICOSN) $(FUSIONSEQGDDIR) $(ROOTSYS)

# ---------------- setup symbols needed in the rest of the file --------

include $(BIOINFOCONFDIR)/biosdefs.make
.SUFFIXES:
SHELL = /bin/sh
O=$(PWD)/obj
B=$(PWD)/bin

ROOTINC = -I$(ROOTSYS)/include/root
ROOTLIB = -L$(ROOTSYS)/lib/root

ROOTFLAGS = -D_REENTRANT -pthread -m64
ROOTLIBS  = $(ROOTLIB) -lCore -lCint -lRIO -lNet -lHist -lGraf \
            -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix \
            -lPhysics -lMathCore -lThread -lfreetype -pthread -lm -ldl

DOXYGEN_BIN_DIR=/home1/lh372/SOFT/doxygen-1.5.7.1/bin

# ----------------------- optional paramters --------
GDDIR	    = $(FUSIONSEQGDDIR)
GDINC	    = -I$(GDDIR)/include
GDLIB       = -L$(GDDIR)/lib
PNGLIB      = -L/usr/lib64
JPEGLIB     = -L/usr/lib64
ZLIB        = -L/usr/lib64
FREETYPELIB = -L/usr/lib64

# ----------------------- entry points --------------

CORE =  $O/geneFusions $O/gfrAnnotationConsistencyFilter $O/gfrLargeScaleHomologyFilter \
	$O/gfrSmallScaleHomologyFilter $O/gfrAbnormalInsertSizeFilter \
	$O/gfrAddInfo  $O/gfrProximityFilter $O/bpFilter $O/bp2alignment \
	$O/gfrPCRFilter $O/gfrBlackListFilter $O/gfr2bpJunctions $O/bowtie2bp \
	$O/gfrConfidenceValues $O/validateBpJunctions $O/gfrExpressionConsistencyFilter \
	$O/gfrMitochondrialFilter $O/gfrRepeatMaskerFilter $O/gfrCountPairTypes \
	$O/gfrRibosomalFilter $O/gfrSpliceJunctionFilter $O/gfrClassify \
	$O/gfrWhiteListFilter

OPTIONAL = $O/gfr2images $O/gfr2bed $O/gfr2fasta $O/gfr2gff $O/bp2wig \
	   $O/plotIntraDistribution $O/export2mrf $O/gfrConfidenceValueTranscript 

CGIS=$O/geneFusions_cgi $O/showDetails_cgi $O/seqViz_cgi $O/findFusionPartner_cgi

TEST =  $B/bp2fasta $B/bpClustering $B/bpValidate $B/quantifierAddInfo \
	$B/quantifier2igv $B/sequenceSelect $B/gfSimulation $B/bowtiePairedFix \
	$B/intervalSize $O/mrfPseudogeneOverlap $B/fixExport \
	$B/extractSpliceJunctionsFromExport $B/test

core: dirs $(CORE) prod

dirs:	
	test -d $O || mkdir $O
	test -d $B || mkdir $B	

all: $(CORE) $(OPTIONAL) prod prod_opts

opts: $(OPTIONAL)

prod:
	/bin/cp $(CORE) $B

prod_opts:
	/bin/cp $(OPTIONAL) $B

clean: 
	/bin/rm -rf $B/*
	/bin/rm -rf $O/*	

cgi: $(CGIS)
	@echo "use 'make deploy' to install the CGIs"

deploy:
	rsync -a --delete $O/geneFusions_cgi $O/showDetails_cgi $O/seqViz_cgi $O/findFusionPartner_cgi  $(FUSIONSEQWEBUSER)@$(FUSIONSEQWEBSERVER):$(FUSIONSEQCGIDIR)/

test: $(TEST)

doxygen: 
	@echo "FusionSeq: documenting code using doxygen."
	@rm -rf html/*
	$(DOXYGEN_BIN_DIR)/doxygen Doxyfile
	rsync -a --delete ./html/ $(FUSIONSEQWEBUSER)@gw.gersteinlab.org:/nfs/web/asboner/public_html/documentation/
	@echo "FusionSeq: documentation finished and released to /nfs/web/asboner/public_html/documentation/"

# -------------------- CORE -----------------------------
# ------------- finding candidate fusions ---------------

$O/geneFusions: geneFusions.c $O/mrf.o $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/geneFusions
	$(CC) $(CFLAGSO) $(BIOSINC) geneFusions.c $O/mrf.o $O/gfr.o -o $O/geneFusions $(BIOSLNK) -lm

$O/gfrExpressionConsistencyFilter: gfrExpressionConsistencyFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrExpressionConsistencyFilter
	$(CC) $(CFLAGSO) $(BIOSINC) -std=c99 gfrExpressionConsistencyFilter.c $O/gfr.o -o $O/gfrExpressionConsistencyFilter $(BIOSLNK) -lm

$O/gfrRibosomalFilter: gfrRibosomalFilter.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrRibosomalFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrRibosomalFilter.c $O/gfr.o $O/util.o -o $O/gfrRibosomalFilter $(BIOSLNK)

$O/gfrMitochondrialFilter: gfrMitochondrialFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrMitochondrialFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrMitochondrialFilter.c $O/gfr.o -o $O/gfrMitochondrialFilter $(BIOSLNK)

$O/gfrLargeScaleHomologyFilter: gfrLargeScaleHomologyFilter.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrLargeScaleHomologyFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrLargeScaleHomologyFilter.c $O/gfr.o $O/util.o -o $O/gfrLargeScaleHomologyFilter $(BIOSLNK)

$O/gfrSmallScaleHomologyFilter: gfrSmallScaleHomologyFilter.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrSmallScaleHomologyFilter 
	$(CC) $(CFLAGSO) $(BIOSINC) gfrSmallScaleHomologyFilter.c $O/gfr.o $O/util.o -o $O/gfrSmallScaleHomologyFilter $(BIOSLNK)

$O/gfrAbnormalInsertSizeFilter: gfrAbnormalInsertSizeFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrAbnormalInsertSizeFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrAbnormalInsertSizeFilter.c $O/gfr.o -o $O/gfrAbnormalInsertSizeFilter $(BIOSLNK)

$O/gfrPCRFilter: gfrPCRFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrPCRFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrPCRFilter.c $O/gfr.o -o $O/gfrPCRFilter $(BIOSLNK)

$O/gfrBlackListFilter: gfrBlackListFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrBlackListFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrBlackListFilter.c $O/gfr.o -o $O/gfrBlackListFilter $(BIOSLNK)

$O/gfrProximityFilter: gfrProximityFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrProximityFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrProximityFilter.c $O/gfr.o -o $O/gfrProximityFilter $(BIOSLNK)

$O/gfrAddInfo: gfrAddInfo.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrAddInfo
	$(CC) $(CFLAGSO) $(BIOSINC) gfrAddInfo.c $O/gfr.o $O/util.o -o $O/gfrAddInfo $(BIOSLNK)

$O/gfrAnnotationConsistencyFilter: gfrAnnotationConsistencyFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrAnnotationConsistencyFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrAnnotationConsistencyFilter.c $O/gfr.o -o $O/gfrAnnotationConsistencyFilter $(BIOSLNK)

$O/gfrConfidenceValues: gfrConfidenceValues.c $O/gfr.o $O/mrf.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrConfidenceValues
	$(CC) $(CFLAGSO) $(BIOSINC) gfrConfidenceValues.c $O/gfr.o $O/mrf.o -o $O/gfrConfidenceValues $(BIOSLNK)

$O/gfrRepeatMaskerFilter: gfrRepeatMaskerFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrRepeatMaskerFilter
	$(CC) $(CFLAGS) $(BIOSINC) gfrRepeatMaskerFilter.c $O/gfr.o -o $O/gfrRepeatMaskerFilter $(BIOSLNK) -lm

$O/gfrCountPairTypes: gfrCountPairTypes.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrCountPairTypes
	$(CC) $(CFLAGSO) $(BIOSINC) gfrCountPairTypes.c $O/gfr.o -o $O/gfrCountPairTypes $(BIOSLNK)

$O/gfrSpliceJunctionFilter: gfrSpliceJunctionFilter.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrSpliceJunctionFilter
	$(CC) $(CFLAGS) $(BIOSINC)  gfrSpliceJunctionFilter.c $O/gfr.o $O/util.o -o $O/gfrSpliceJunctionFilter $(BIOSLNK) 

$O/gfrClassify: gfrClassify.c $O/gfr.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $B/gfrClassify
	$(CC) $(CFLAGSO) $(BIOSINC) gfrClassify.c $O/util.o $O/gfr.o -o $O/gfrClassify -lm $(BIOSLNK)

$O/gfrWhiteListFilter: gfrWhiteListFilter.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfrWhiteListFilter
	$(CC) $(CFLAGSO) $(BIOSINC) gfrWhiteListFilter.c $O/gfr.o -o $O/gfrWhiteListFilter $(BIOSLNK)


# --------------------- identifying sequence of the junction --------------------------

$O/gfr2bpJunctions: gfr2bpJunctions.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfr2bpJunctions
	$(CC) $(CFLAGSO) $(BIOSINC) gfr2bpJunctions.c $O/gfr.o -o $O/gfr2bpJunctions $(BIOSLNK) -lm

$O/bowtie2bp: bowtie2bp.c $(BIOSLIB)
	-@/bin/rm -f $O/bowtie2bp
	$(CC) $(CFLAGSO) $(BIOSINC) bowtie2bp.c -o $O/bowtie2bp $(BIOSLNK)

$O/validateBpJunctions: validateBpJunctions.c $O/bp.o $(BIOSLIB)
	-@/bin/rm -f $O/validateBpJunctions
	$(CC) $(CFLAGSO) $(BIOSINC) validateBpJunctions.c $O/bp.o -o $O/validateBpJunctions $(BIOSLNK)

$O/bpFilter: bpFilter.c $O/bp.o $(BIOSLIB)
	-@/bin/rm -f $O/bpFilter.o $O/bpFilter
	g++ $(ROOTFLAGS) $(BIOSINC) $(ROOTINC) -c bpFilter.c -o $O/bpFilter.o
	$(CC) -lstdc++ $O/bpFilter.o $O/bp.o -o $O/bpFilter $(BIOSLNK) $(ROOTLIBS)	

$O/bp2alignment: bp2alignment.c $O/bp.o $(BIOSLIB)
	-@/bin/rm -f $O/bp2alignment
	$(CC) $(CFLAGSO) $(BIOSINC) bp2alignment.c $O/bp.o -o $O/bp2alignment $(BIOSLNK)


# ----------------------------- OPTIONAL ----------------------------------

$O/plotIntraDistribution: plotIntraDistribution.c $(BIOSLIB)
	-@/bin/rm -f $O/plotIntraDistribution.o $O/plotIntraDistribution
	g++ $(ROOTFLAGS) $(BIOSINC) $(ROOTINC) -c plotIntraDistribution.c -o $O/plotIntraDistribution.o
	$(CC) -lstdc++ $O/plotIntraDistribution.o -o $O/plotIntraDistribution $(BIOSLNK) $(ROOTLIBS)

$O/gfr2images: gfr2images.c $O/gfr.o $(GDDIR)/include/gd.h $(GDDIR)/include/gdfontmb.h $(BIOSLIB)
	-@/bin/rm -f $O/gfr2images
	$(CC) $(CFLAGSO) $(BIOSINC) $(GDINC) gfr2images.c $O/gfr.o -o $O/gfr2images $(BIOSLNK) $(GDLIB) $(PNGLIB) $(JPEGLIB) $(ZLIB) $(FREETYPELIB) -lgd -lpng -lz -ljpeg -lfreetype -lm

$O/gfr2bed: gfr2bed.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfr2bed
	$(CC) $(CFLAGSO) $(BIOSINC) gfr2bed.c $O/gfr.o -o $O/gfr2bed $(BIOSLNK)

$O/gfr2fasta: gfr2fasta.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfr2fasta
	$(CC) $(CFLAGSO) $(BIOSINC) gfr2fasta.c $O/gfr.o -o $O/gfr2fasta $(BIOSLNK)

$O/gfr2gff: gfr2gff.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/gfr2gff
	$(CC) $(CFLAGSO) $(BIOSINC) gfr2gff.c $O/gfr.o -o $O/gfr2gff $(BIOSLNK)

$O/bp2wig: bp2wig.c $O/bp.o $(BIOSLIB)
	-@/bin/rm -f $O/bp2wig
	$(CC) $(CFLAGSO) $(BIOSINC) bp2wig.c $O/bp.o -o $O/bp2wig $(BIOSLNK)

$O/export2mrf: export2mrf.c $O/mrf.o $(BIOSLIB)
	-@/bin/rm -f $O/export2mrf
	$(CC) $(CFLAGSO) $(BIOSINC) export2mrf.c -o $O/export2mrf $(BIOSLNK)

$O/gfrConfidenceValueTranscript: gfrConfidenceValueTranscript.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $B/gfrConfidenceValueTranscript
	$(CC) $(CFLAGSO) $(BIOSINC) gfrConfidenceValueTranscript.c $O/gfr.o -o $O/gfrConfidenceValueTranscript -lm $(BIOSLNK)


# ---------------------------- CGI ---------------------------------------------
$O/geneFusions_cgi: geneFusions_cgi.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/geneFusions_cgi
	$(CC) $(CFLAGSO) $(BIOSINC) $(FUSIONSEQCGITARGET) geneFusions_cgi.c $O/gfr.o -o $O/geneFusions_cgi $(BIOSLNK)

$O/showDetails_cgi: showDetails_cgi.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f showDetails_cgi
	$(CC) $(CFLAGSO) $(BIOSINC) $(FUSIONSEQCGITARGET) showDetails_cgi.c $O/gfr.o -o $O/showDetails_cgi $(BIOSLNK)

$O/seqViz_cgi: seqViz_cgi.c $O/mrf.o $O/segmentationUtil.o $O/sqvWeb.o $O/sqvUtil.o $O/sqvCircos.o $(BIOSLIB)
	-@/bin/rm -f seqViz_cgi
	$(CC) $(CFLAGSO) $(BIOSINC) $(FUSIONSEQCGITARGET) seqViz_cgi.c $O/mrf.o $O/segmentationUtil.o $O/sqvWeb.o $O/sqvUtil.o $O/sqvCircos.o -o $O/seqViz_cgi -lm  $(BIOSLNK)

$O/findFusionPartner_cgi: findFusionPartner_cgi.c $O/gfr.o $(BIOSLIB)
	-@/bin/rm -f $O/findFusionPartner_cgi
	$(CC) $(CFLAGSO) $(BIOSINC) $(FUSIONSEQCGITARGET) findFusionPartner_cgi.c $O/gfr.o -o $O/findFusionPartner_cgi $(BIOSLNK)


# ---------------------------- COMMON LIBRARIES ---------------------------------
$O/gfr.o: gfr.c gfr.h $(BIOSLIB)  
	-@/bin/rm -f $O/gfr.o
	$(CC) $(CFLAGSO) $(BIOSINC) gfr.c -c -o $O/gfr.o

$O/mrf.o: mrf.c mrf.h $(BIOSLIB)  
	-@/bin/rm -f $O/mrf.o
	$(CC) $(CFLAGSO) $(BIOSINC) mrf.c -c -o $O/mrf.o

$O/segmentationUtil.o: segmentationUtil.c segmentationUtil.h $(BIOSLIB)  
	-@/bin/rm -f $O/segmentationUtil.o
	$(CC) $(CFLAGSO) $(BIOSINC) segmentationUtil.c -c -o $O/segmentationUtil.o

$O/util.o: util.c util.h $(BIOSLIB)  
	-@/bin/rm -f $O/util.o
	$(CC) $(CFLAGSO) $(BIOSINC) util.c -c -o $O/util.o

$O/bp.o: bp.c bp.h $(BIOSLIB)  
	-@/bin/rm -f $O/bp.o
	$(CC) $(CFLAGSO) $(BIOSINC) bp.c -c -o $O/bp.o

$O/sqvWeb.o: sqvWeb.c sqvWeb.h sqvUtil.h $(BIOSLIB)
	-@/bin/rm -f $O/sqvWeb.o
	$(CC) $(CFLAGSO) $(BIOSINC) sqvWeb.c -c -o $O/sqvWeb.o

$O/sqvUtil.o: sqvUtil.c sqvUtil.h sqvWeb.h $(BIOSLIB)
	-@/bin/rm -f $O/sqvUtil.o
	$(CC) $(CFLAGSO) $(BIOSINC) sqvUtil.c -c -o $O/sqvUtil.o

$O/sqvCircos.o: sqvCircos.c sqvCircos.h sqvUtil.h $(BIOSLIB)
	-@/bin/rm -f $O/sqvCircos.o
	$(CC) $(CFLAGSO) $(BIOSINC) sqvCircos.c -c -o $O/sqvCircos.o



# ---------------------------- TEST ---------------------------------
# $B/sequenceSelect: sequenceSelect.c $O/mrf.o $(BIOSLIB)
#	-@/bin/rm -f $B/sequenceSelect
#	$(CC) $(CFLAGSO) $(BIOSINC) sequenceSelect.c $O/mrf.o -o $B/sequenceSelect -lm $(BIOSLNK)

$B/gfSimulation: gfSimulation.c $O/mrf.o $(BIOSLIB)
	-@/bin/rm -f $B/gfSimulation
	$(CC) $(CFLAGS) $(BIOSINC) gfSimulation.c $O/mrf.o -o $B/gfSimulation -lm $(BIOSLNK)

# $B/bowtiePairedFix: bowtiePairedFix.c $(BIOSLIB)
#	-@/bin/rm -f $B/bowtiePairedFix
#	$(CC) $(CFLAGSO) $(BIOSINC) bowtiePairedFix.c -o $B/bowtiePairedFix $(BIOSLNK)

# $B/intervalSize: intervalSize.c  $(BIOSLIB)
#	-@/bin/rm -f $B/intervalSize
#	$(CC) $(CFLAGSO) $(BIOSINC) intervalSize.c  -o $B/intervalSize $(BIOSLNK)  -lm

$O/mrfPseudogeneOverlap: mrfPseudogeneOverlap.c $O/mrf.o $(BIOSLIB)
	-@/bin/rm -f $O/mrfPseudogeneOverlap
	$(CC) $(CFLAGSO) $(BIOSINC) mrfPseudogeneOverlap.c $O/mrf.o -o $O/mrfPseudogeneOverlap $(BIOSLNK) -lm

$B/quantifierAddInfo: quantifierAddInfo.c $O/mrf.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $B/quantifierAddInfo
	$(CC) $(CFLAGSO) $(BIOSINC) quantifierAddInfo.c $O/util.o -o $B/quantifierAddInfo $(BIOSLNK)

#$B/quantifier2igv: quantifier2igv.c $O/mrf.o $O/util.o $(BIOSLIB)
#	-@/bin/rm -f $B/quantifier2igv
#	$(CC) $(CFLAGS) $(BIOSINC) quantifier2igv.c $O/util.o -o $B/quantifier2igv $(BIOSLNK) -lm

$B/bp2fasta: bp2fasta.c $O/bp.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $B/bp2fasta
	$(CC) $(CFLAGS) $(BIOSINC) bp2fasta.c $O/bp.o -o $B/bp2fasta $(BIOSLNK) -lm

$B/bpClustering: bpClustering.c $O/bp.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $B/bpClustering
	$(CC) $(CFLAGS) $(BIOSINC) bpClustering.c $O/bp.o -o $B/bpClustering $(BIOSLNK) -lm

$B/bpValidate: bpValidate.c $O/bp.o $O/util.o $(BIOSLIB)
	-@/bin/rm -f $B/bpValidate
	$(CC) $(CFLAGS) $(BIOSINC) bpValidate.c $O/bp.o -o $B/bpValidate $(BIOSLNK) -lm

#$iB/fixExport: fixExport.c $(BIOSLIB)
#	-@/bin/rm -f $B/fixExport
#	$(CC) $(CFLAGS) $(BIOSINC) fixExport.c -o $B/fixExport $(BIOSLNK)

#$B/extractSpliceJunctionsFromExport: extractSpliceJunctionsFromExport.c $(BIOSLIB)
#	-@/bin/rm -f $B/extractSpliceJunctionsFromExport
#	$(CC) $(CFLAGS) $(BIOSINC) extractSpliceJunctionsFromExport.c -o $B/extractSpliceJunctionsFromExport $(BIOSLNK)

#$B/test: test.c $(BIOSLIB)
#	-@/bin/rm -f $B/test
#	$(CC) $(CFLAGS) $(BIOSINC) test.c -o $B/test $(BIOSLNK)
