lib_LTLIBRARIES = libfusionseq.la
libfusionseq_la_SOURCES = bp.c \
			  gfr.c \
			  sqvCircos.c \
			  sqvUtil.c \
			  sqvWeb.c \
			  util.c

libfusionseq_la_LIBADD = 

include_HEADERS = bp.h \
		  bfr.h \
		  sqvCircos.h \
		  sqvUtil.h \
		  sqvWeb.h \
		  util.h


